name: Marketplace release

on: workflow_dispatch

jobs:
  build:
    runs-on: [self-hosted, radu]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v5
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_TOKEN }}
      - name: Point npm at the internal registry
        run: jf npmc --repo-resolve=npm-dynatrace-release-v
      - name: Install all
        run: npm run install:all
      - name: Build everything
        run: npm run build:all
      - name: Package all targets
        run: |
          for target in \
            win32-x64 \
            linux-x64 \
            linux-arm64 \
            linux-armhf \
            alpine-x64 \
            alpine-arm64 \
            darwin-x64 \
            darwin-arm64; do
            echo "Packaging $target"
            npx vsce package --no-dependencies --target "$target"
          done
      - uses: actions/upload-artifact@v7
        with:
          name: vsix-packages
          path: "*.vsix"
          archive: false

  publish:
    runs-on: [self-hosted, radu]
    needs: build
    if: success()
    steps:
      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v5
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_TOKEN }}
      - name: Point npm at the internal registry
        run: jf npmc --repo-resolve=npm-dynatrace-release-v
      - uses: actions/download-artifact@v8
      - name: Publish to VSCode Marketplace
        run: |
          for vsix in $(find . -iname '*.vsix'); do
            npx vsce publish --packagePath "$vsix"
          done
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
      - name: Publish to OpenVSX
        run: |
          for vsix in $(find . -iname '*.vsix'); do
            npx ovsx publish --packagePath "$vsix"
          done
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
